# Generated by Django 4.1 on 2022-09-25 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('contraseña', models.CharField(max_length=18)),
                ('fecha_cre', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30)),
                ('ubicacion', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('nit', models.IntegerField()),
                ('ciudad', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('sector_p', models.EmailField(max_length=45, unique=True)),
                ('fecha_cre', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('codigo_mov', models.IntegerField(auto_created=True)),
                ('empresa', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('ingresos', models.IntegerField()),
                ('egresos', models.IntegerField()),
                ('fecha_hora', models.DateField(auto_now=True)),
                ('usuario', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('contador', models.IntegerField(primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=18)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=18)),
                ('empresa', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('fecha_cre', models.DateField(auto_now=True)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.movimientos')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('usuario', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=20)),
                ('apellido', models.TextField(max_length=20)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField(null=True)),
                ('contraseña', models.CharField(max_length=18)),
                ('fecha_cre', models.DateField(auto_now=True)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.empresas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.movimientos')),
            ],
        ),
    ]
