# Generated by Django 4.1 on 2022-09-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='sector_p',
            field=models.CharField(max_length=45),
        ),
    ]
