# Generated by Django 4.1 on 2022-09-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_alter_empresas_sector_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='empresa',
            field=models.CharField(max_length=45),
        ),
    ]
