# Generated by Django 4.1 on 2022-09-26 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_empleado_codigo_alter_empleado_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.empresas'),
        ),
        migrations.AlterField(
            model_name='login',
            name='contador',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='login',
            name='usuario',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='codigo_mov',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movimientos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.empleado'),
        ),
    ]
