# Generated by Django 4.1 on 2022-09-26 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_empresas_codigo_alter_gerente_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='nombre',
            new_name='empresa',
        ),
    ]
