# Generated by Django 4.1 on 2022-09-27 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_rename_nombre_empresas_empresa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimientos',
        ),
    ]
