# Generated by Django 4.1 on 2022-09-27 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_delete_movimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('codigo_mov', models.AutoField(primary_key=True, serialize=False)),
                ('ingresos', models.IntegerField()),
                ('egresos', models.IntegerField()),
                ('fecha_hora', models.DateField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.empresas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.empleado')),
            ],
        ),
    ]
