# Generated by Django 4.1 on 2022-10-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_movimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='concepto',
            field=models.TextField(max_length=45, null=True),
        ),
    ]
